### PR TITLE
get height from grpc metadata for relevant ibc queries

### PR DESCRIPTION
**Pull request by noot**
## Checklist before requesting a review

- [ ] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

  > REPLACE THIS TEXT WITH RATIONALE (CAN BE BRIEF)

### CODE REVIEW

**Review by SuperFluffy — COMMENTED** [review]
High level comment: it looks like parsing the height info from the grpc metadata is duplicated 5 times.

Maybe this patch could be streamlined by replacing it with a single function?

Also: fix the warnings please.

**Comment by SuperFluffy** [comment]
@noot I have replaced the 5 instances of inline code by a single function call and provided tests, and also fixed the warnings.

**Comment by SuperFluffy** [comment]
I have fixed the test by treating the absence of a height header the same as a value of `"0"` or `"0-0"`. This fixes the failing test.

**Comment by noot** [comment]
closing in favour of #2

**Pull request closed without merging**
